### ISSUE TITLE
intelmetool.c:20:10: fatal error: pci/pci.h: No such file or directory

### ISSUE THREAD

**Issue by Futureknows** [zamaudio/intelmetool#14]
When I try to build the tool using make I get the following error:

`[user@localhost intelmetool-main]$ make
gcc -Wall -O0 -g -I. -c intelmetool.c  -o intelmetool.o
intelmetool.c:20:10: fatal error: pci/pci.h: No such file or directory
 #include <pci/pci.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:25: intelmetool.o] Error 1
`

Running Fedora 26

**Comment by eloydegen** [comment]
On Fedora you have to install the `pciutils-devel` package.

**Comment by Futureknows** [comment]
That solved it thanks!
