### ISSUE TITLE
Intel E3815: Hardware unsupported by intelmetool, exiting

### ISSUE THREAD

**Issue by ProBackup-nl** [zamaudio/intelmetool#16]
I unloaded `mei` and `mei_txt` modules, and `cat /proc/cmdline` contains 'iomem=relaxed'.

The `./intelmetool` output is short:

> Hardware unsupported by intelmetool, exiting

DE3815TYKH, BIOS TYBYT10H.86A.0054.2016.0929.15 is inside.

**Comment by zamaudio** [comment]
Hi thanks for report, can you please show output for:
```
lspci -nn | grep -E "00:00.0|LPC"
```

**Comment by ProBackup-nl** [comment]
`00:00.0 Host bridge [0600]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register [8086:0f00] (rev 0c)`

**Comment by zamaudio** [comment]
Okay it is not detecting your board because it doesnt have a separate Southbridge.

**Comment by zamaudio** [comment]
But you probably do have the ME hardware and a pci MEI.

**Comment by ProBackup-nl** [comment]
```
# lsmod | grep me
mei_txe                24576  0
mei                   114688  1 mei_txe
# modinfo mei | grep description
description:    Intel(R) Management Engine Interface
# modinfo mei_txe | grep description
description:    Intel(R) Trusted Execution Environment Interface
```
