### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by flipmess** [zamaudio/intelmetool#7]
hi. i get:
`Bad news, you have a `QM77 Express Chipset LPC Controller` so you have ME hardware on board and it is very difficult to remove, continuing...
Error mapping physical memory 0x00000000fed1c000[0x4000] ERRNO=1
RCBA at 0xfed1c000
[1]    27537 segmentation fault (core dumped)  ./intelmetool`

on lenovo W530 (Linux  4.7.0-1-ARCH #1 SMP PREEMPT  x86_64 GNU/Linux)

**Comment by diggit** [comment]
I have same problem on Thinkpad T430. `(4.6.4-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux )`

**Comment by zamaudio** [comment]
Hi folks, please `sudo rmmod mei_me` and `sudo rmmod mei` before using this tool.

**Comment by dogtopus** [comment]
Also try to pass `iomem=relaxed` to kernel if you are on kernel 4.4+ (https://www.flashrom.org/FAQ)

**Comment by DavidoRotho** [comment]
Same issue on Thinkpad x220

Linux: 4.9.11-1-ARCH x86_64
On: Arch GNU/Linux

**Comment by zamaudio** [comment]
Updated readme, closing.
